site_name: InnoMaker
site_url: https://wiki.inno-maker.com
### Navigation
Nav:
- Home: index.md
- Raspberry PI Series: Raspberry PI Series
- USB Cameras: USB Cameras.md
- USB Logic Analyzer: USB Logic Analyzer
- USB TO CAN: USB TO CAN.md

theme:
  name: mkdocs

markdown_extentions:
  - admonition

plugins:
  - search

extra_css:
  - resources/css/extra.css

copyright: |
  &copy; 2023 <a href="https://www.inno-maker.com"  target="_blank" rel="noopener">InnoMaker</a>
