site_name: InnoMaker
site_url: https://wiki.inno-maker.com
### Navigation
nav:
- Home: index.md
- Raspberry PI Series:  ###一级标题
  - Cameras: Raspberry_PI_Series/cameras.md ### 二级标题：目录／文件名
  - Audios: Raspberry_PI_Series/audios.md
- USB TO CAN: 
  - USB TO CAN: USB_TO_CAN/USB_TO_CAN.md
- USB Cameras: 
  - UVC Series: USB_Cameras/uvc-series.md
  - U3V Series: USB_Cameras/u3v-series.md
- Brand Products:
  - USB Logic Analyzer: Brand_Products/USB_Logic_Analyzer.md

theme:
  name: mkdocs

markdown_extentions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

extra_css:
  - resources/css/extra.css

copyright: |
  &copy; 2023 <a href="https://www.inno-maker.com"  target="_blank" rel="noopener">InnoMaker</a>
